name: Itartusa
favicon: null
layout_spectrum: 0.75442
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebeae6'
    - '#c0bcbd'
    - '#878f92'
    - '#585e5c'
    - '#881e11'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
