name: Itartusa
favicon: null
layout_spectrum: 0
typography_spectrum: 0.07252
title: Itartusa Inc. - Italian Art in USA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebeae6'
    - '#c0bcbd'
    - '#878f92'
    - '#585e5c'
    - '#881e11'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
