name: Itartusa
favicon: null
layout_spectrum: 0.8194618786219507
typography_spectrum: 0.004784218734130263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3367481885943562
  lightness: 0.5355978624429554
  saturation: 0.6630839430727065
  rhythmicContrast: 0.311682615429163
purpose: []
